import { supabaseAdmin } from "@/integrations/supabase/client.server";
import {
  checkSharedPublicQuota,
  type PublicActionScope,
  type QuotaDecision,
  type RpcReply,
} from "@/lib/shared-public-quota";

/**
 * Server-only adapter; service role must never be exposed to the browser.
 * SUPABASE_* keys remain server-side; flags are not VITE_ variables.
 *
 * TypeScript types are regenerated by the connected Supabase integration.
 * Avoid editing the generated Database type by hand prior to migration:
 * describe this one server-side function signature locally.
 */
type RestrictedQuotaRpc = {
  rpc: (
    functionName: "somman_try_public_action",
    parameters: { p_scope: PublicActionScope },
  ) => PromiseLike<RpcReply>;
};

export async function consumeSharedPublicQuota(
  scope: PublicActionScope,
): Promise<QuotaDecision> {
  const enabled = process.env["SOMMAN_SHARED_QUOTA_ENABLED"] === "true";
  return checkSharedPublicQuota({
    enabled,
    invoke: async () => {
      const admin = supabaseAdmin as unknown as RestrictedQuotaRpc;
      return await admin.rpc("somman_try_public_action", { p_scope: scope });
    },
  });
}
